apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gitops-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "apps.pocarqnube.com"
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "apps.pocarqnube.com"